name: OCI Image

on:
  push:
    branches:
      - master

jobs:
  chekout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
