name: OCI Image

on:
  push:
    branches:
      - master

jobs:
  Build-OCI-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          submodules: recursive
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rmuhamedgaliev/telegram-bot-api
      - name: Get version
        id: current-version
        run: |
          TG_SERVER_VERSION=$(cat telegram-bot-api/CMakeLists.txt | grep TelegramBotApi | cut -d " " -f3)
          echo "TG_SERVER_VERSION=${TG_SERVER_VERSION}" >> $GITHUB_ENV
          echo "Parsed version: ${TG_SERVER_VERSION}"
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: telegram-bot-api
          tags: |
            rmuhamedgaliev/telegram-bot-api:latest
            rmuhamedgaliev/telegram-bot-api:${{ env.TG_SERVER_VERSION }}
          containerfiles: ./Containerfile
      - name: Push To Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: index.docker.io/v2/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

